# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8f924a931f6e410f4f693d64601454bdec472c9169ad971630232c19aa439c67025c03c93024dfb0a7b9e4ae1aca3e591325b85bdf4893a8ded2488d4a55a9d

test:
  secret_key_base: 717e5af06c5e4496756f059ea11dd523918670b101577ecd2692cd83ae68ae941d1c01880d5c4e30e605a8ae484758e7389857d504c890b2cf4d8c0184f3800a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
